### ISSUE TITLE
Source code???

### ISSUE THREAD

**Issue by unilock** [Loxoz/BetterWaystonesMenu#1]
Hi! I saw this mod on Modrinth, and thought it looked really neat. But unfortunately I don't use 1.18.2 anymore.

So I did what any normal person would do and decompiled the mod, ported it to Architectury Loom, and updated it for 1.19.2. Now I can use it in my own private modpack :)

Unfortunately that sort of violates the mod's ARR license. I was hoping you'd consider relicensing the code with something more permissible, and maybe even publishing the source code?

(If you're interested in my fork, I can grant complete and total permission to take it and do what you will with it. Not like I had permission to make it in the first place. (rather ask for forgiveness than for permission... or something like that))

**Comment by Loxoz** [comment]
Ok so yes this mod will be open source, it's just that in a rush to post before I had to go I didn't push the code and set the license to ARR for now, but you saying "decompile" like a normal person is funny when actual open source projects don't even get pull requests from other users.
As I said in the description under the picture, I don't have that much time to put into this mod, I just made it for fun and experiments, it's also an attempt to get it to some QSMP members or QSMP modpack which itself runs on 1.18.2 as their waystone menu are so messed up.
I posted the mod literally 3 days ago and I didn't expect to have someone like you at 6 downloads lol.
Anyway, I made the addon directly for Forge only because I tried to make a mod with Architectury Loom not so long ago and had problems with it, I don't remember exactly what, but it made me make this mod with Forge gradle only, even the original mod supports both Fabric and Forge, and I've actually made more Fabric mods than Forge lately, so you might have seen some Fabric like named variables.
Also I'm still not finished with the stuff I want to implement so won't update until I'm done with it.
But like I said, since this mod will be open source and you successfully made it work with Architectury, you can contact me on discord so we can talk about it further. (you can find the link on my [InGameStats](https://modrinth.com/mod/ingamestats) or my [ContainerSearcher](https://modrinth.com/mod/csearcher) mods at the bottom)

**Comment by unilock** [comment]
> ...but you saying "decompile" like a normal person is funny when actual open source projects don't even get pull requests from other users.

I have a tendency to do things sometimes. Bad habit :p

> But like I said, since this mod will be open source and you successfully made it work with Architectury...

Note that I didn't get it working with Architectury *API;* just Architectury Loom (I'm still only building it for Forge).   
Though it shouldn't be *too* difficult to accomplish the former - but Fabric has [fwaystones](https://modrinth.com/mod/fwaystones), which already has a much better GUI, so I don't think it's all that necessary.

> ...you can contact me on discord so we can talk about it further.

I see you released a new version of this mod the other day, and having access to the source code would make it a lot easier to update my own fork, so yes - will do :)
